# Generated by Django 3.1.7 on 2021-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_auto_20210612_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceites',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='baterias',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='filtros',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen', verbose_name='imagen'),
        ),
    ]
